Repository dot-layer/blog, pull requests merged in 2020-07, with the labels that each got.

#114 Small fixes - language bugs
  content/bookshelf/_index.en.md
  content/contact/_index.en.md
  i18n/en.toml
  i18n/fr.toml
  layouts/404.html
  layouts/contact/list.html
Labels: bug

#115 Traduction du How to contribute en EN
  HOWTO.md
  content/blog/2020-03-19-howto/index.en.md
  content/blog/2020-03-19-howto/index.fr.md
  static/img/headers/howto-cover.png
Labels: enhancement

#116 Fix min-width screen & icon sizes
  config.toml
  content/about/_index.en.md
  content/about/_index.fr.md
  layouts/partials/footer-category.html
  layouts/partials/social.html
  static/css/add-on.css
  static/css/main.css
Labels: bug

#121 Hide share-nav
  layouts/partials/navbar.html
Labels: bug

#122 Change comportement btn language
  content/blog/2020-03-04-what-is-wrong-with-sklearn/index.en.md
  layouts/partials/language-switcher.html
  static/css/add-on.css
  static/css/main.css
Labels: enhancement

#123 Add How to git -- FIXESSSS
  content/contribute/_index.en.md
  content/contribute/_index.fr.md
  i18n/en.toml
  i18n/fr.toml
  layouts/book/single.html
  layouts/itemized/single.html
  layouts/partials/form/contribute.html
  layouts/partials/navbar.html
  layouts/partials/share-menu.html
  layouts/post/single.html
  static/css/add-on.css
  static/css/main.css
  static/js/main.js
Labels: bug

#117 Rss
  layouts/_default/rss.xml
  layouts/partials/header.html
Labels: enhancement

#126 Fix link in Contribute
  i18n/en.toml
  i18n/fr.toml
  layouts/404.html
  layouts/partials/form/contribute.html
  static/css/404.css
Labels: bug

#128 Fix rss
  layouts/404.html
  layouts/_default/rss.xml
  static/css/404.css
Labels: bug

#113 Post/n g københavn
  content/blog/2020-06-09/index.fr.md
  static/img/headers/copenhagen-fr-cover.jpg
  static/img/headers/nico.jpg
Labels: new post
